export const msg = {
  uploadFrontIdentityImages: "Upload front identity image",
  uploadBackIdentityImages: "Upload back identity image",
  uploadProfImg: "Upload profile image",
  uploadProfImgParent: "Upload Parent profile image",
  uploadFrontIdentityImageForParent: "Upload front identity image for Parent",
  uploadBackIdentityImageForParent: "Upload back identity image for Parent",
  uploadFrontIdentityImageForChild: "Upload front identity image for Child",
  uploadBackIdentityImageForChild: "Upload back identity image for Child",
  uploadProfImageForChild: "Upload Profile image for Child",
  uploadFrontAndBackIdentityImages: "Upload front and back identity images",
  userAlreadyExistWithEmail: "User already exist with same email.",
  loginSuccess: "Login successfully.",
  otpSentToEmail: "OTP sent to your email address",
  otpExpired: "OTP expired",
  otpNotAvailable: "OTP not available",
  otpInvalid: "OTP invalid",
  userNotFound: "User not found.",
  recordNotFound: "Record not found.",
  inCorrectPassword: "Incorrect password.",
  otpLength: (length: number) => `OTP must be ${length} long`,
  uploadMedicalReport: "Please upload a medical report file",
  prescriptionRequestSuccess: "Prescription requested successfully.",
  rejectSuccess: "Record rejected successfully.",
  atLeast1MedSerOrLab:
    "At least one of medicine, service, or laboratory must be provided",
  ejsFileNotFound: "EJS file not found",
  errGenPdf: "Error generating PDF",
  failToGenBarcode: "Failed to generate barcode",
  prescriptionSaveSuccess: "Prescription saved successfully",
  registerSuccess: "Register Successfully.",
};
